services:
    # --- Banco de Dados ---
    postgres:
        image: postgres:15-alpine
        container_name: autoflex-postgres
        environment:
            POSTGRES_DB: inventory_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: autoflexTESTE
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - autoflex-network

    # --- Backend (API Quarkus) ---
    backend:
        container_name: autoflex-api
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.jvm
        ports:
            - "8080:8080"
        environment:
            QUARKUS_DATASOURCE_DB_KIND: postgresql
            QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/inventory_db
            QUARKUS_HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY: drop-and-create
        depends_on:
            - postgres
        networks:
            - autoflex-network

volumes:
    postgres_data:


networks:
    autoflex-network:
        driver: bridge
